# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1300, 700)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.window_title = QtWidgets.QLabel(Form)
        self.window_title.setEnabled(True)
        self.window_title.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.window_title.setFont(font)
        self.window_title.setObjectName("window_title")
        self.verticalLayout.addWidget(self.window_title)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.widget)
        self.tabWidget.setObjectName("tabWidget")
        self.google_tab = QtWidgets.QWidget()
        self.google_tab.setObjectName("google_tab")
        self.tabWidget.addTab(self.google_tab, "")
        self.deepl_tab = QtWidgets.QWidget()
        self.deepl_tab.setObjectName("deepl_tab")
        self.tabWidget.addTab(self.deepl_tab, "")
        self.baidu_tab = QtWidgets.QWidget()
        self.baidu_tab.setObjectName("baidu_tab")
        self.tabWidget.addTab(self.baidu_tab, "")
        self.youdao_tab = QtWidgets.QWidget()
        self.youdao_tab.setObjectName("youdao_tab")
        self.tabWidget.addTab(self.youdao_tab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "翻译软件2.0"))
        self.window_title.setText(_translate("Form", "翻译软件 2.0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.google_tab), _translate("Form", "Google"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.deepl_tab), _translate("Form", "DeepL"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.baidu_tab), _translate("Form", "百度"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.youdao_tab), _translate("Form", "有道"))
